name: amap_location_fluttify_example
description: Demonstrates how to use the amap_location_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  decorated_flutter: ^0.18.0
  permission_handler: ^4.3.0

#dependency_overrides:
#  foundation_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/foundation_fluttify
#  core_location_fluttify:
#    path: /Users/yohom/Github/Me/All/fluttify/fluttify_infra/core_location_fluttify

dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_location_fluttify:
    path: ../

flutter:
  uses-material-design: true