name: amap_location_fluttify_example
description: Demonstrates how to use the amap_location_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  decorated_flutter: ^0.10.0
  permission_handler: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_location_fluttify:
    path: ../

flutter:
  uses-material-design: true