name: amap_location_fluttify
description: An `Amap` Location Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.
version: 0.20.0-dev.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_location_fluttify

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  amap_core_fluttify: ^0.14.0-dev.0
  
  foundation_fluttify: ^0.11.0-dev.0
  core_location_fluttify: ^0.6.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_location_fluttify
        pluginClass: AmapLocationFluttifyPlugin
      ios:
        pluginClass: AmapLocationFluttifyPlugin